version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
    restart: on-failure
###< doctrine/doctrine-bundle ###
  apache:
    ports:
      - "80:80"
